name: Generate README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - run: |
          julia  -e 'using Pkg; Pkg.add("BenchmarkTools"); Pkg.develop(path="."); include("./benchmark/generate_README.jl")'
          echo $(git diff) 
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Update benchmarks in README"
          add: README.md benchmark/params.json